name: App deploy

on: workflow_dispatch

jobs:

  # ci:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image and Push to ACR test
  #     run: |
  #       docker build . --file Dockerfile --tag my-r-shiny-app:latest
  #       docker tag my-r-shiny-app:latest azuremlhuduaa31f772f.azurecr.io/my-r-shiny-app:latest
  #       az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.SECRET }} --tenant ${{ secrets.TENANTID }}
  #       az acr login -n azuremlhuduaa31f772f
  #       docker push azuremlhuduaa31f772f.azurecr.io/my-r-shiny-app:latest
  cd:
    # needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run app in App Service from ACR test
      run: |
        az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.SECRET }} --tenant ${{ secrets.TENANTID }}
        az webapp up --runtime PYTHON:3.11 --sku B3 --name webappstatscantest --resource-group statscan-chatbot-mtc-app-rg     
